name: Test, Build, Publish
on: push
jobs:
  test-build-publish:
    environment: deploy
    name: Publish distributions to Test PyPI and PyPI
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: 3.9
    - name: Run tests
      run: make test
    - name: Build a binary wheel and a source tarball
      run: |
        make prep-package
        make package
    - name: Publish distribution to Test PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository_url: https://test.pypi.org/legacy/
        skip_existing: true
    - name: Publish distribution to PyPI
      if: startsWith(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
